########################################################
#                                                      #
# | \ | |      by Jackdaw1101                          #
# |  \| |/ _ \/ _ \| '_ \      Main Configuration For  #
# | |\  |  __/ (_) | | | |     Neon Databases!         #
# |_| \_|\___|\___/|_| |_|     (1.0)                   #
########################################################
#
# You can add more database types via API of features
# For instance, Chat Toggle System have this option
# (!) Databases cannot be reloaded with /neon reload
#
########################################################
#                         GLOBAL                       #
########################################################
#
# Database settings
# available SQLite, MySQL. MongoDB (lowecase)
DATABASE:
  TYPE: "sqlite"
#
# Mongo DB Settings
MONGODB:
  DATABASE: "Neon"
  URL: "mongodb://localhost:27017"
#
# MySQL Settings
MYSQL:
  HOST: "localhost"
  PORT: 3306
  DATABASE: "database"
  USERNAME: "root"
  PASSWORD: "veryHardPassWord1"
  #
  # Do not modify these if you don't know what your doing
  USE-SSL: false
  AUTO-RECONNECT: true
  FAIL-OVER-RED-ONLY: true
  MAX-RECONNECTS: 10
#
# SQLite database (.db is added in the code)
SQLITE-CHATTOGGLE:
  NAME: "chat_toggle"
